#!/usr/bin/env bash

main() {
  set -eo pipefail; [[ "$TRACE" ]] && set -x

  local version="$1"
  local directory="${2:-/usr/loca/rubies}"

  ruby-build "$version" "$directory/$version"
  cd "$directory/$version"
  mkdir -p "$directory/packaged"
  tar cf "$directory/packaged/$version.tar" "."
}

main $@
